prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    additionalScrapeConfigs:
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        scrape_timeout: 30s
        static_configs:
          - targets: ['api-gateway.spring-petclinic-ireland.svc.cluster.local:8080']

      - job_name: 'customers-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['customers-service.spring-petclinic-ireland.svc.cluster.local:8081']

      - job_name: 'vets-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['vets-service.spring-petclinic-ireland.svc.cluster.local:8083']

      - job_name: 'visits-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['visits-service.spring-petclinic-ireland.svc.cluster.local:8082']

      - job_name: 'config-server'
        metrics_path: '/actuator/prometheus'
        params:
          format: ['prometheus']
        static_configs:
          - targets: ['config-server.spring-petclinic-ireland.svc.cluster.local:8888']

      - job_name: 'genai-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['genai-service.spring-petclinic-ireland.svc.cluster.local:8084']

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: MyStrongPassword123
  service:
    type: ClusterIP
